name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test-sauce
        env:
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      - run: scripts/ci-after-success-hook.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_KEY_VIVLIOSTYLE_ORG: ${{ secrets.DEPLOY_KEY_VIVLIOSTYLE_ORG }}
          DEPLOY_KEY_VIVLIOSTYLE_GITHUB_IO: ${{ secrets.DEPLOY_KEY_VIVLIOSTYLE_GITHUB_IO }}
